export const products = [
  {
    slug: "ezzy-cartz",
    name: "Ezzy Cartz",
    description: "A comprehensive e-commerce solution for modern businesses",
    image: "https://www.mcodevbytes.in/ezzy-cart-logo.png",
    features: [
      "Easily create and customize your online store without coding.",
      "Smart AI suggests relevant products based on customer preferences.",
      "Accept payments through multiple options (UPI, credit/debit cards, wallets, etc.).",
      "Customers and sellers can track orders live from purchase to delivery.",
      "Optimized for mobile devices with a quick checkout process.",
    ],
    demoUrl: "https://www.ezzycartz.com/",
    benefits: [
      "Get your business online quickly, saving time and money on development.",
      "Boosts sales by offering a personalized shopping experience.",
      "Increases customer convenience, leading to higher conversions.",
      "Enhances trust and transparency, improving customer satisfaction.",
      "Reduces cart abandonment, ensuring a smooth shopping experience.",
    ],
  },
  {
    slug: "host-my-cv",
    name: "Host My CV",
    description: "Professional online resume hosting and management platform",
    image: "https://www.mcodevbytes.in/host-my-cv-logo.png",
    features: [
      "Create and host your professional CV with a unique link.",
      "Choose from a variety of stylish and professional CV designs.",
      "Edit and update your CV in real-time.",
      "Your CV gets an SEO-friendly URL for better visibility.",
      "See who viewed and interacted with your CV.",
    ],
    demoUrl: "https://www.hostmycv.in/",
    benefits: [
      "Share your resume easily with recruiters and employers anytime, anywhere.",
      "Make a great first impression with a resume that stands out.",
      "No need to resend PDFs—your latest version is always online.",
      "Increase your chances of being discovered by recruiters through search engines.",
      "Get insights into recruiter interest and follow up effectively.",
    ],
  },
  {
    slug: "creator-mind",
    name: "Creator Mind",
    description: "All-in-one platform for content creators and digital artists",
    image: "https://www.mcodevbytes.in/creator-mind-logo.png",
    features: [
      "Get AI-driven suggestions for content, designs, or business ideas.",
      "Built-in tools for image, video, and text editing with smart enhancements.",
      "Connect, share, and collaborate with other creators in real time.",
      "Integrated analytics, branding, and monetization features.",
      "Directly publish content to social media, blogs, and websites.",
    ],
    demoUrl: "https://meta.mcodevbytes.in/",
    benefits: [
      "Saves time and helps creators overcome creative blocks effortlessly.",
      "Makes professional-level content creation quick and easy.",
      "Expand your network, get feedback, and grow your creative influence.",
      "Helps creators turn their passion into a profitable business.",
      "Saves time and ensures a wider reach with just one click.",
    ],
  },
] 